### ISSUE TITLE
关于Azure的支持

### ISSUE THREAD

**Issue by pitayaIsGood** [devlive-community/openai-java-sdk#38]
能否说明一下如果要使用微软提供的api，需要做些什么配置上的修改

**Comment by qianmoQ** [comment]
可以参考一下示例：https://github.com/devlive-community/openai-java-sdk/blob/dev/src/test/java/org/devlive/sdk/openai/AzureOpenAiClientTest.java
修改配置：

apiHost 设置为在 Azure 设置的资源服务地址
provider 设置为 ProviderModel.AZURE
version 设置为在 Azure 创建的资源版本
apiKey 配置的密钥
model 使用的模型

修改以上配置即可

**Comment by PengMai1998** [comment]
org.devlive.sdk.openai.exception.RequestException: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.

我的deploymentOrModelId = "CUG_Lab408_GPT"，我能不能自定义CompletionModel类将我自己的模型名字加进去

**Comment by PengMai1998** [comment]
你好，请问消息输出到一半就终止，怎么解决？输出到一半就输出[DONE]了

**Comment by PengMai1998** [comment]
![image](https://github.com/devlive-community/openai-java-sdk/assets/66857677/a5b7fd29-e61e-46b1-9dd7-598f5b8295e3)
![image](https://github.com/devlive-community/openai-java-sdk/assets/66857677/93844836-296c-4ea3-9440-8b691a909939)

**Comment by qianmoQ** [comment]
这个是因为 token 数过大导致的，需要修改支持更多 token 数量的 model

**Comment by PengMai1998** [comment]
> 这个是因为 token 数过大导致的，需要修改支持更多 token 数量的 model

我检查了以下，model是够用的。token数是指发送给openAI的token太多了吗？

**Comment by qianmoQ** [comment]
> > 这个是因为 token 数过大导致的，需要修改支持更多 token 数量的 model
> 
> 我检查了以下，model是够用的。token数是指发送给openAI的token太多了吗？

是的

**Comment by pitayaIsGood** [comment]
> > 这个是因为 token 数过大导致的，需要修改支持更多 token 数量的 model
> 
> 我检查了以下，model是够用的。token数是指发送给openAI的token太多了吗？

也许你可以看看这个项目  做了Azure的整合并且处理了token数超出限制的问题：https://github.com/Pitayafruits/springboot-AzureOpenAi-sdk

**Comment by PengMai1998** [comment]
非常感谢，我已经解决了

**Comment by qianmoQ** [comment]
> > > 这个是因为 token 数过大导致的，需要修改支持更多 token 数量的 model
> > 
> > 
> > 我检查了以下，model是够用的。token数是指发送给openAI的token太多了吗？
> 
> 也许你可以看看这个项目 做了Azure的整合并且处理了token数超出限制的问题：https://github.com/Pitayafruits/springboot-AzureOpenAi-sdk

框架是默认不会处理模型 token的配置。需要用户执行特定的 token 来解决
